# Generated by Django 5.1.4 on 2024-12-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_salesrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
