# Generated by Django 5.1.4 on 2024-12-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_salesrecord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchorder',
            name='batch_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
