# Generated by Django 5.1.4 on 2024-12-18 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_salesrecord_sale_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-delivery_id'], 'verbose_name_plural': 'Delivery Records'},
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='date_recorded',
            new_name='date_added',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
