# Generated by Django 5.1.4 on 2024-12-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchorder',
            name='batch_total',
        ),
        migrations.AddField(
            model_name='batchorder',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchorderitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='salesrecorditem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='salesrecorditem',
            name='surcharge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
    ]
