# Generated by Django 5.1.4 on 2024-12-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_batchorder_batch_total_batchorder_grand_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
    ]
