# Generated by Django 5.1.4 on 2024-12-18 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_delivery_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='client_name',
        ),
        migrations.AddField(
            model_name='delivery',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='main.client'),
        ),
    ]
