# Generated by Django 5.1.4 on 2024-12-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_product_cost_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity_left',
            new_name='quantity',
        ),
    ]
