# Generated by Django 5.1.4 on 2024-12-18 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_delivery_client_name_delivery_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='client',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='client',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salesrecorditem',
            name='sales_record',
        ),
        migrations.RemoveField(
            model_name='salesrecorditem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='SalesRecord',
        ),
        migrations.DeleteModel(
            name='SalesRecordItem',
        ),
    ]
