# Generated by Django 5.1.4 on 2024-12-18 03:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_delivery_client_remove_salesrecord_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('date_claimed', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='delivery/images/')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='main.client')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Delivery Records',
                'ordering': ['-delivery_id'],
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(editable=False)),
                ('net_day', models.PositiveIntegerField(choices=[(0, 'Net 0'), (15, 'Net 15'), (30, 'Net 30'), (60, 'Net 60'), (90, 'Net 90')], default=30)),
                ('invoice_image', models.ImageField(blank=True, null=True, upload_to='invoice/images/')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=60)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_records', to='main.client')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Record',
                'verbose_name_plural': 'Sales Records',
                'ordering': ['-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='SalesRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('surcharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_items', to='main.product')),
                ('sales_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.salesrecord')),
            ],
            options={
                'verbose_name': 'Sales Record Item',
                'verbose_name_plural': 'Sales Record Items',
            },
        ),
    ]
