# Generated by Django 5.1.4 on 2024-12-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_quantity_left_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchorder',
            old_name='supplied_date',
            new_name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='batchorderitem',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='batchorderitem',
            name='defectives',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchorderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='net_day',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
