# Generated by Django 5.1.4 on 2024-12-27 15:54

import django.db.models.deletion
import django.utils.timezone
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_supplied_date_batchorder_purchase_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchorderitem',
            name='defectives',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='invoice_image',
        ),
        migrations.AddField(
            model_name='batchorderitem',
            name='defective',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='image',
            field=models.ImageField(default='defaults/no_image.png', upload_to='invoices/images/'),
        ),
        migrations.AddField(
            model_name='salesrecorditem',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesrecorditem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesrecorditem',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='batchorder',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='batchorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_orders', to='main.supplier'),
        ),
        migrations.AlterField(
            model_name='batchorderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_items', to='main.product'),
        ),
        migrations.AlterField(
            model_name='batchorderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='main.client'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date_claimed',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='image',
            field=models.ImageField(blank=True, default='defaults/no_image.png', null=True, upload_to='deliveries/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='critical_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='defaults/no_image.png', upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.unit'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_records', to='main.client'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='due_date',
            field=models.DateField(default=main.models.get_default_due_date),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesrecorditem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_items', to='main.product'),
        ),
        migrations.AlterField(
            model_name='salesrecorditem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.TextField(blank=True, default=''),
        ),
    ]
