# Generated by Django 5.1.4 on 2024-12-30 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_product_cost_price_alter_product_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchorderitem',
            name='batch',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='main.batchorder'),
        ),
    ]
