# Generated by Django 5.1.4 on 2024-12-30 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_batchorderitem_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchorderitem',
            name='batch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.batchorder'),
            preserve_default=False,
        ),
    ]
