# Generated by Django 5.1.4 on 2024-12-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_batchorderitem_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
