# Generated by Django 5.1.4 on 2025-01-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='batchorder',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
