# Generated by Django 5.1.4 on 2025-01-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_product_supplier_alter_batchorder_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchorder',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
