# Generated by Django 5.1.4 on 2025-01-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_batchorder_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='client_address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='client',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
