# Generated by Django 5.1.4 on 2025-01-05 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_salesrecord_client_address_alter_salesrecord_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='client',
        ),
        migrations.AlterModelOptions(
            name='salesrecorditem',
            options={},
        ),
        migrations.AddField(
            model_name='delivery',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='main.salesrecord'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date_claimed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
