# Generated by Django 5.1.4 on 2025-01-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_delivery_client_alter_salesrecorditem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesrecorditem',
            old_name='amount',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='image',
            field=models.ImageField(default='defaults/no_image.png', upload_to='deliveries/images/'),
        ),
    ]
