# Generated by Django 5.1.4 on 2025-01-06 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='client_address',
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.client'),
        ),
    ]
