# Generated by Django 5.1.4 on 2025-01-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_dailysales_weeklysales_monthlysales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date_claimed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
