# Generated by Django 5.1.4 on 2025-05-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_delivery_date_claimed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='invoices/images/'),
        ),
    ]
