# Generated by Django 5.1.4 on 2025-05-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_batchorder_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchorder',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
