# Generated by Django 5.1.4 on 2025-05-28 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_batchorder_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchorder',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_orders', to='main.supplier'),
        ),
    ]
